theme: pages-themes/minimal@v0.2.0
title: ""
description: ""
show_downloads: false
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
